
server:
  port: 5500

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/license_tracker
    username: root
    password: Roshan@20

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: licensetracker-super-secret-key-32chars-min
  expiration: 86400000
  logging:
    level:
      org.springframework.security: DEBUG


